#!/bin/bash

filesInDir () {
    local folderPath="${1%/}"
    local files=$( ls $folderPath )
    local filesFiltered=""

    for i in $files ; do
        if [ -d "$1/$i" ] ; then
            filesFiltered="$filesFiltered$(filesInDir $folderPath/$i)"
            continue
        fi
        if [ -f "$1/$i" ] ; then
            filesFiltered="$filesFiltered$folderPath/$i "
        fi
    done

    echo "$filesFiltered"
}

echo "Monitoring files:"
monitored_files=""
for f in "$@"
do
    if [ -d "$f" ] ; then
        echo "folder: $f"
        monitored_files="$monitored_files $(filesInDir $f)"
        shift
        continue
    fi
    if [ ! -f "$f" ] ; then
        break
    fi
    monitored_files="$monitored_files $f"
    shift
done
for f in $monitored_files ; do
    echo "$f"
done

echo ""

echo "and running commands:"
for c in "$@"
do
    echo $c
done

echo ""

inotifywait -m -e close_write $monitored_files | 
while read -r filename event
# while inotifywait -e close_write $monitored_files
do

    for cmd in "$@"
    do
        bash -c "$cmd"
    done
done

